import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import {cn} from '@/lib/utils'

const fontSans = Plus_Jakarta_Sans({
  subsets:['latin'],
  weight: ['300','400','500','600'],
  variable:'--font-sans'
})

export const metadata: Metadata = {
  title: "Health Care",
  description: "Generated by Magar Ltd.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* cn is short form for className, help to add dynamix/static class names */}
      <body className={cn('min-h-screen font-sans antialiased', fontSans.variable)}>{children}</body>
    </html>
  );
}
